---
title: "Homework 2 - Solutions"
author: "[Solutions]{style='background-color: yellow;'}"
toc: true
title-block-banner: true
title-block-style: default
execute: 
  freeze: true
  cache: true
format: html
---

[Link to the Github repository](https://github.com/psu-stat380/hw-2)

---

::: {.callout-important style="font-size: 0.8em;" collapse="true"}
## Due: Tue, Feb 14, 2023 @ 11:59pm

Please read the instructions carefully before submitting your assignment.

1. This assignment requires you to only upload a `PDF` file on Canvas
1. Don't collapse any code cells before submitting. 
1. Remember to make sure all your code output is rendered properly before uploading your submission.

⚠️ Please add your name to the author information in the frontmatter before submitting your assignment ⚠️
:::

For this assignment, we will be using the [Abalone dataset](http://archive.ics.uci.edu/ml/datasets/Abalone) from the UCI Machine Learning Repository. The dataset consists of physical measurements of abalone (a type of marine snail) and includes information on the age, sex, and size of the abalone.

We will be using the following libraries:

```{R}
library(readr)
library(tidyr)
library(ggplot2)
library(dplyr)
library(purrr)
library(cowplot)
```


<br><br><br><br>
---

## Question 1
::: {.callout-tip}
## 30 points
EDA using `readr`, `tidyr` and `ggplot2`
:::

###### 1.1 (5 points)

Load the "Abalone" dataset as a tibble called `abalone` using the URL provided below. The `abalone_col_names` variable contains a vector of the column names for this dataset (to be consistent with the R naming pattern). Make sure you read the dataset with the provided column names. 

```{R}
library(readr)
url <- "http://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"

abalone_col_names <- c(
  "sex", 
  "length", 
  "diameter", 
  "height", 
  "whole_weight", 
  "shucked_weight", 
  "viscera_weight", 
  "shell_weight", 
  "rings"
)

abalone <- read_csv(url, col_names = abalone_col_names);
abalone
```

---

###### 1.2 (5 points)

Remove missing values and `NA`s from the dataset and store the cleaned data in a tibble called `df`. How many rows were dropped?

```{R}
df <- abalone %>% 
drop_na()

nrow(abalone) - nrow(df)
```




---

##### 1.3 (5 points)

Plot histograms of all the quantitative variables in a **single plot** [^footnote_facet_wrap]


```{R}
df %>% 
  select(where(is.numeric)) %>% 
  gather() %>% 
  ggplot(.) +
  geom_histogram(aes(value)) +
  facet_wrap(~key, scales = 'free_x')
```


---

##### 1.4 (5 points)

First, initialize a `ggplot2` object:

```{R}
p <- ggplot(df)
```


Create a boxplot of `length` for each `sex` and create a violin-plot of of `diameter` for each `sex`. 

```{R}
p + geom_boxplot(aes(y=length, fill=sex))
```

```{R}
p + geom_violin(aes(y=diameter, x=sex, fill=sex))
```

Are there any notable differences in the physical appearences of abalones based on your analysis here?

> Not really

---

###### 1.5  (5 points)

Create a scatter plot of `length` and `diameter`, and modify the shape and color of the points based on the `sex` variable. Change the size of each point based on the `shell_wight` value for each observation.




```{R}
p + 
  geom_point(
    aes(x=length, y=height, group=sex, color=sex, shape=sex, size=shell_weight), alpha=0.5
  )
```

Are there any notable anomalies in the dataset?

> 2 notable outliers in the dataset

---

###### 1.6 (5 points)

For each `sex`, create separate scatter plots of `length` and `diameter`. For each plot, also add a **linear** trendline to illustrate the relationship between the variables. Use the `facet_wrap()` function in R for this, and ensure that the plots are vertically stacked **not** horizontally. You should end up with a plot that looks like this: [^footnote_plot_facet]


```{R}
p + 
  geom_point(aes(x=length, y=height, shape=sex, color=sex)) + 
  geom_smooth(aes(x=length, y=height), method=lm) +
  facet_wrap(~sex, 3, 1)
```





<br><br><br><br>
<br><br><br><br>
---

## Question 2
::: {.callout-tip}
## 40 points
More advanced analyses using `dplyr`, `purrrr` and `ggplot2`
:::


---

###### 2.1 (10 points)

Filter the data to only include abalone with a length of at least $0.5$ meters. Group the data by `sex` and calculate the mean of each variable for each group. Create a bar plot to visualize the mean values for each variable by `sex`.


```{R}
df %>% 
  filter(length >= 0.5) %>% 
  group_by(sex) %>% 
  summarise_if(is.numeric, mean, na.rm=TRUE) %>% 
  pivot_longer(-c(sex)) %>% 
  ggplot(.) + 
    geom_bar(
      aes(x=name, y=value, fill=sex), 
      stat='identity', position='dodge'
    )
```


---

###### 2.2 (15 points)

Implement the following in a **single command**:

1. Temporarily create a new variable called `num_rings` which takes a value of:

  * `"low"` if `rings < 10`
  * `"high"` if `rings > 20`, and
  * `"med"` otherwise

2. Group `df` by this new variable and `sex` and compute `avg_weight` as the average of the `whole_weight + shucked_weight + viscera_weight + shell_weight` for each combination of `num_rings` and `sex`. 

3. Use the `geom_tile()` function to create a tile plot of `num_rings` vs `sex` with the color indicating of each tile indicating the `avg_weight` value. 


```{R}
df %>% 
  mutate(
    num_rings = case_when(
    rings < 10 ~ "low", 
    rings > 20 ~ "high", 
    TRUE ~ "med")
  ) %>% 
  group_by(num_rings, sex) %>% 
  summarise(
    avg_weight = mean(
    whole_weight + 
    shucked_weight + 
    viscera_weight + 
    shell_weight
    )
  ) %>% 
  mutate(
    num_rings = factor(
      num_rings, 
      levels=c("low", "med", "high")
      )
    ) %>%
  ggplot(.) + geom_tile(aes(x=num_rings, y=sex, fill=avg_weight))
```



---

###### 2.3 (5 points)

Make a table of the pairwise correlations between all the numeric variables rounded to 2 decimal points. Your final answer should look like this [^footnote_table]


```{R}
df %>% 
  select(where(is.numeric)) %>% 
  cor() %>%
  round(digits=2) %>% 
  knitr::kable()
```



---

###### 2.4 (10 points)

Use the `map2()` function from the `purrr` package to create a scatter plot for each _quantitative_ variable against the number of `rings` variable. Color the points based on the `sex` of each abalone. You can use the `cowplot::plot_grid()` function to finally make the following grid of plots.


```{R}
df %>% 
  select(where(is.numeric)) %>% 
  map2(
    ., colnames(.),
    ~{
      ggplot(df) + 
      geom_point(aes(x = rings, y=., color=sex)) +
      ggtitle(as.character(.y))
    }
  ) %>% 
  cowplot::plot_grid(plotlist=.)
```



<br><br><br><br>
<br><br><br><br>
---

## Question 3
::: {.callout-tip}
## 30 points

Linear regression using `lm`
:::

---

###### 3.1 (10 points)

Perform a simple linear regression with `diameter` as the covariate and `height` as the response. Interpret the model coefficients and their significance values. 


```{R}
model <- lm(height ~ diameter, df)
summary(model)
```

```{R}
#| echo: false
#| output: asis
library(report)
report(model)
```




---

###### 3.2 (10 points)

Make a scatterplot of `height` vs `diameter` and plot the regression line in `color="red"`. You can use the base `plot()` function in R for this. Is the linear model an appropriate fit for this relationship? Explain. 


```{R}
plot(height ~ diameter, df, pch=20)
abline(model, col="red")
```



---

###### 3.3  (10 points)

Suppose we have collected observations for "new" abalones with `new_diameter` values given below. What is the expected value of their `height` based on your model above? Plot these new observations along with your predictions in your plot from earlier using `color="violet"`

```{R}

new_diameters <- c(
  0.15218946,
  0.48361548,
  0.58095513,
  0.07603687,
  0.50234599,
  0.83462092,
  0.95681938,
  0.92906875,
  0.94245437,
  0.01209518
)

new_data_frame <- data.frame(diameter=new_diameters)
new_heights <- predict(model, new_data_frame)
```

```{R}
plot(height ~ diameter, df, pch=20)
abline(model, col="red")
abline(v=new_diameters, col="purple")
points(new_diameters, new_heights, col="purple", pch=20, cex=2)
```




:::{.hidden unless-format="pdf"}
\pagebreak
:::

<br><br><br><br>
<br><br><br><br>
---


# Appendix

::: {.callout-note collapse="true"}
## Session Information

Print your `R` session information using the following command

```{R}
sessionInfo()
```
:::

[^footnote_facet_wrap]:
  You can use the `facet_wrap()` function for this. Have a look at its documentation using the help console in R

[^footnote_plot_facet]:
  Plot example for 1.6<br>

[^footnote_table]:
  Table for 2.3